import { type NextRequest, NextResponse } from "next/server"

interface HealthSystem {
  id: string
  name: string
  location: string
  type: "hospital" | "health_system" | "clinic" | "snf"
  beds: number
  referralsThisMonth: number
  referralsLastMonth: number
  acceptanceRate: number
  avgResponseTime: number
  integrationStatus: "active" | "pending" | "inactive"
  channels: string[]
  contactPerson: string
  phone: string
  email: string
  lastContact: string
  priority: "high" | "medium" | "low"
  estimatedMonthlyValue: number
}

const healthSystems: HealthSystem[] = [
  // MAJOR HEALTH SYSTEMS
  {
    id: "beaumont",
    name: "Corewell Health (Beaumont)",
    location: "Royal Oak, MI",
    type: "health_system",
    beds: 1200,
    referralsThisMonth: 45,
    referralsLastMonth: 38,
    acceptanceRate: 78,
    avgResponseTime: 2.3,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "fax", "phone"],
    contactPerson: "Sarah Mitchell, RN",
    phone: "(248) 898-5000",
    email: "referrals@corewell.org",
    lastContact: "2024-01-15",
    priority: "high",
    estimatedMonthlyValue: 125000,
  },
  {
    id: "henry_ford",
    name: "Henry Ford Health System",
    location: "Detroit, MI",
    type: "health_system",
    beds: 2800,
    referralsThisMonth: 67,
    referralsLastMonth: 52,
    acceptanceRate: 82,
    avgResponseTime: 1.8,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "secure_messaging", "phone"],
    contactPerson: "Dr. Michael Johnson",
    phone: "(313) 916-2600",
    email: "discharge.planning@henryford.com",
    lastContact: "2024-01-14",
    priority: "high",
    estimatedMonthlyValue: 185000,
  },
  {
    id: "umich",
    name: "University of Michigan Health",
    location: "Ann Arbor, MI",
    type: "health_system",
    beds: 1000,
    referralsThisMonth: 32,
    referralsLastMonth: 28,
    acceptanceRate: 85,
    avgResponseTime: 2.1,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "fax"],
    contactPerson: "Lisa Chen, MSW",
    phone: "(734) 936-4000",
    email: "homecare.referrals@med.umich.edu",
    lastContact: "2024-01-13",
    priority: "high",
    estimatedMonthlyValue: 95000,
  },
  {
    id: "mclaren",
    name: "McLaren Health Care",
    location: "Flint, MI",
    type: "health_system",
    beds: 800,
    referralsThisMonth: 28,
    referralsLastMonth: 22,
    acceptanceRate: 75,
    avgResponseTime: 2.8,
    integrationStatus: "pending",
    channels: ["email", "fax", "phone"],
    contactPerson: "Jennifer Adams, RN",
    phone: "(810) 342-2000",
    email: "case.management@mclaren.org",
    lastContact: "2024-01-12",
    priority: "medium",
    estimatedMonthlyValue: 78000,
  },
  {
    id: "spectrum",
    name: "Corewell Health (Spectrum)",
    location: "Grand Rapids, MI",
    type: "health_system",
    beds: 900,
    referralsThisMonth: 38,
    referralsLastMonth: 31,
    acceptanceRate: 80,
    avgResponseTime: 2.2,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "phone"],
    contactPerson: "Robert Wilson, MSW",
    phone: "(616) 391-1774",
    email: "referrals@spectrumhealth.org",
    lastContact: "2024-01-15",
    priority: "high",
    estimatedMonthlyValue: 105000,
  },
  {
    id: "ascension",
    name: "Ascension Michigan",
    location: "Warren, MI",
    type: "health_system",
    beds: 1500,
    referralsThisMonth: 41,
    referralsLastMonth: 35,
    acceptanceRate: 77,
    avgResponseTime: 2.5,
    integrationStatus: "active",
    channels: ["email", "fax", "phone", "secure_messaging"],
    contactPerson: "Maria Rodriguez, RN",
    phone: "(586) 573-5000",
    email: "homehealth@ascension.org",
    lastContact: "2024-01-14",
    priority: "high",
    estimatedMonthlyValue: 115000,
  },
  {
    id: "trinity",
    name: "Trinity Health Michigan",
    location: "Livonia, MI",
    type: "health_system",
    beds: 700,
    referralsThisMonth: 25,
    referralsLastMonth: 20,
    acceptanceRate: 73,
    avgResponseTime: 3.1,
    integrationStatus: "pending",
    channels: ["email", "fax", "phone"],
    contactPerson: "David Thompson, MSW",
    phone: "(734) 343-1000",
    email: "referrals@trinity-health.org",
    lastContact: "2024-01-11",
    priority: "medium",
    estimatedMonthlyValue: 68000,
  },
  {
    id: "munson",
    name: "Munson Healthcare",
    location: "Traverse City, MI",
    type: "health_system",
    beds: 400,
    referralsThisMonth: 18,
    referralsLastMonth: 15,
    acceptanceRate: 88,
    avgResponseTime: 1.9,
    integrationStatus: "active",
    channels: ["email", "phone", "fax"],
    contactPerson: "Amanda Foster, RN",
    phone: "(231) 935-5000",
    email: "discharge@munsonhealthcare.org",
    lastContact: "2024-01-13",
    priority: "medium",
    estimatedMonthlyValue: 52000,
  },
  {
    id: "bronson",
    name: "Bronson Healthcare",
    location: "Kalamazoo, MI",
    type: "health_system",
    beds: 600,
    referralsThisMonth: 22,
    referralsLastMonth: 18,
    acceptanceRate: 79,
    avgResponseTime: 2.4,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "fax", "phone"],
    contactPerson: "Jessica Brown, MSW",
    phone: "(269) 341-6000",
    email: "referrals@bronsonhg.org",
    lastContact: "2024-01-14",
    priority: "high",
    estimatedMonthlyValue: 64000,
  },
  {
    id: "sparrow",
    name: "Sparrow Health System",
    location: "Lansing, MI",
    type: "health_system",
    beds: 500,
    referralsThisMonth: 19,
    referralsLastMonth: 16,
    acceptanceRate: 81,
    avgResponseTime: 2.2,
    integrationStatus: "active",
    channels: ["email", "fax", "phone"],
    contactPerson: "Mark Davis, RN",
    phone: "(517) 364-1000",
    email: "discharge@sparrow.org",
    lastContact: "2024-01-13",
    priority: "medium",
    estimatedMonthlyValue: 58000,
  },
  {
    id: "mercy_health",
    name: "Mercy Health",
    location: "Muskegon, MI",
    type: "health_system",
    beds: 450,
    referralsThisMonth: 16,
    referralsLastMonth: 14,
    acceptanceRate: 76,
    avgResponseTime: 2.6,
    integrationStatus: "pending",
    channels: ["email", "fax", "phone"],
    contactPerson: "Nancy Wilson, MSW",
    phone: "(231) 672-2000",
    email: "referrals@mercyhealth.com",
    lastContact: "2024-01-12",
    priority: "medium",
    estimatedMonthlyValue: 48000,
  },

  // REHABILITATION HOSPITALS
  {
    id: "mary_free_bed",
    name: "Mary Free Bed Rehabilitation Hospital",
    location: "Grand Rapids, MI",
    type: "hospital",
    beds: 80,
    referralsThisMonth: 34,
    referralsLastMonth: 29,
    acceptanceRate: 92,
    avgResponseTime: 1.5,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "phone"],
    contactPerson: "Dr. Sarah Johnson",
    phone: "(616) 840-8000",
    email: "discharge@maryfreebed.com",
    lastContact: "2024-01-15",
    priority: "high",
    estimatedMonthlyValue: 95000,
  },
  {
    id: "rim_detroit",
    name: "Rehabilitation Institute of Michigan",
    location: "Detroit, MI",
    type: "hospital",
    beds: 60,
    referralsThisMonth: 28,
    referralsLastMonth: 24,
    acceptanceRate: 89,
    avgResponseTime: 1.7,
    integrationStatus: "active",
    channels: ["email", "fax", "phone"],
    contactPerson: "Dr. Michael Chen",
    phone: "(313) 745-1203",
    email: "referrals@rimrehab.org",
    lastContact: "2024-01-14",
    priority: "high",
    estimatedMonthlyValue: 78000,
  },
  {
    id: "select_specialty",
    name: "Select Specialty Hospital",
    location: "Pontiac, MI",
    type: "hospital",
    beds: 40,
    referralsThisMonth: 21,
    referralsLastMonth: 18,
    acceptanceRate: 85,
    avgResponseTime: 2.1,
    integrationStatus: "active",
    channels: ["email", "fax", "phone"],
    contactPerson: "Linda Martinez, RN",
    phone: "(248) 452-5000",
    email: "discharge@selectspecialty.com",
    lastContact: "2024-01-13",
    priority: "medium",
    estimatedMonthlyValue: 58000,
  },
  {
    id: "kindred_detroit",
    name: "Kindred Hospital Detroit",
    location: "Detroit, MI",
    type: "hospital",
    beds: 77,
    referralsThisMonth: 26,
    referralsLastMonth: 22,
    acceptanceRate: 83,
    avgResponseTime: 2.3,
    integrationStatus: "pending",
    channels: ["email", "fax", "phone"],
    contactPerson: "Robert Taylor, MSW",
    phone: "(313) 473-6000",
    email: "referrals@kindred.com",
    lastContact: "2024-01-12",
    priority: "medium",
    estimatedMonthlyValue: 72000,
  },
  {
    id: "encompass_health",
    name: "Encompass Health Rehabilitation",
    location: "Novi, MI",
    type: "hospital",
    beds: 50,
    referralsThisMonth: 19,
    referralsLastMonth: 16,
    acceptanceRate: 87,
    avgResponseTime: 1.9,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Jennifer Adams, RN",
    phone: "(248) 735-8000",
    email: "discharge@encompasshealth.com",
    lastContact: "2024-01-14",
    priority: "medium",
    estimatedMonthlyValue: 53000,
  },

  // SKILLED NURSING FACILITIES
  {
    id: "genesis_healthcare",
    name: "Genesis HealthCare - Multiple Locations",
    location: "Statewide, MI",
    type: "snf",
    beds: 2400,
    referralsThisMonth: 89,
    referralsLastMonth: 76,
    acceptanceRate: 71,
    avgResponseTime: 3.2,
    integrationStatus: "active",
    channels: ["email", "fax", "phone"],
    contactPerson: "Mary Johnson, DON",
    phone: "(248) 555-0100",
    email: "referrals@genesishcc.com",
    lastContact: "2024-01-15",
    priority: "high",
    estimatedMonthlyValue: 245000,
  },
  {
    id: "trilogy_health",
    name: "Trilogy Health Services",
    location: "Multiple Locations, MI",
    type: "snf",
    beds: 1800,
    referralsThisMonth: 67,
    referralsLastMonth: 58,
    acceptanceRate: 74,
    avgResponseTime: 2.9,
    integrationStatus: "active",
    channels: ["email", "fax", "phone"],
    contactPerson: "Susan Davis, RN",
    phone: "(616) 555-0200",
    email: "discharge@trilogyhs.com",
    lastContact: "2024-01-14",
    priority: "high",
    estimatedMonthlyValue: 185000,
  },
  {
    id: "american_house",
    name: "American House Senior Living",
    location: "Multiple Locations, MI",
    type: "snf",
    beds: 1200,
    referralsThisMonth: 45,
    referralsLastMonth: 39,
    acceptanceRate: 68,
    avgResponseTime: 3.5,
    integrationStatus: "pending",
    channels: ["email", "fax", "phone"],
    contactPerson: "Patricia Wilson, MSW",
    phone: "(248) 555-0300",
    email: "referrals@americanhouse.com",
    lastContact: "2024-01-13",
    priority: "medium",
    estimatedMonthlyValue: 124000,
  },
  {
    id: "sunrise_senior",
    name: "Sunrise Senior Living",
    location: "Multiple Locations, MI",
    type: "snf",
    beds: 800,
    referralsThisMonth: 32,
    referralsLastMonth: 28,
    acceptanceRate: 72,
    avgResponseTime: 3.1,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Karen Brown, DON",
    phone: "(248) 555-0400",
    email: "discharge@sunriseseniorliving.com",
    lastContact: "2024-01-12",
    priority: "medium",
    estimatedMonthlyValue: 88000,
  },
  {
    id: "brookdale",
    name: "Brookdale Senior Living",
    location: "Multiple Locations, MI",
    type: "snf",
    beds: 1500,
    referralsThisMonth: 56,
    referralsLastMonth: 48,
    acceptanceRate: 69,
    avgResponseTime: 3.4,
    integrationStatus: "active",
    channels: ["email", "fax", "phone"],
    contactPerson: "Michelle Taylor, RN",
    phone: "(313) 555-0500",
    email: "referrals@brookdale.com",
    lastContact: "2024-01-14",
    priority: "medium",
    estimatedMonthlyValue: 154000,
  },
  {
    id: "five_star",
    name: "Five Star Senior Living",
    location: "Multiple Locations, MI",
    type: "snf",
    beds: 900,
    referralsThisMonth: 38,
    referralsLastMonth: 33,
    acceptanceRate: 70,
    avgResponseTime: 3.3,
    integrationStatus: "pending",
    channels: ["email", "fax", "phone"],
    contactPerson: "David Martinez, MSW",
    phone: "(616) 555-0600",
    email: "discharge@fivestarseniorliving.com",
    lastContact: "2024-01-11",
    priority: "medium",
    estimatedMonthlyValue: 105000,
  },
  {
    id: "hcr_manorcare",
    name: "HCR ManorCare",
    location: "Multiple Locations, MI",
    type: "snf",
    beds: 1100,
    referralsThisMonth: 42,
    referralsLastMonth: 36,
    acceptanceRate: 73,
    avgResponseTime: 3.0,
    integrationStatus: "active",
    channels: ["email", "fax", "phone"],
    contactPerson: "Lisa Anderson, DON",
    phone: "(248) 555-0700",
    email: "referrals@hcr-manorcare.com",
    lastContact: "2024-01-13",
    priority: "medium",
    estimatedMonthlyValue: 116000,
  },
  {
    id: "life_care_centers",
    name: "Life Care Centers of America",
    location: "Multiple Locations, MI",
    type: "snf",
    beds: 600,
    referralsThisMonth: 24,
    referralsLastMonth: 21,
    acceptanceRate: 75,
    avgResponseTime: 2.8,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Nancy Garcia, RN",
    phone: "(517) 555-0800",
    email: "discharge@lcca.com",
    lastContact: "2024-01-12",
    priority: "medium",
    estimatedMonthlyValue: 66000,
  },

  // SPECIALTY HOSPITALS
  {
    id: "childrens_michigan",
    name: "Children's Hospital of Michigan",
    location: "Detroit, MI",
    type: "hospital",
    beds: 230,
    referralsThisMonth: 15,
    referralsLastMonth: 12,
    acceptanceRate: 94,
    avgResponseTime: 1.2,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "phone"],
    contactPerson: "Dr. Emily Chen, MD",
    phone: "(313) 745-5437",
    email: "pediatric.discharge@dmc.org",
    lastContact: "2024-01-15",
    priority: "high",
    estimatedMonthlyValue: 42000,
  },
  {
    id: "beaumont_childrens",
    name: "Beaumont Children's Hospital",
    location: "Royal Oak, MI",
    type: "hospital",
    beds: 160,
    referralsThisMonth: 12,
    referralsLastMonth: 10,
    acceptanceRate: 91,
    avgResponseTime: 1.4,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "phone"],
    contactPerson: "Dr. Sarah Williams, MD",
    phone: "(248) 898-4000",
    email: "peds.referrals@beaumont.org",
    lastContact: "2024-01-14",
    priority: "high",
    estimatedMonthlyValue: 33000,
  },
  {
    id: "mott_childrens",
    name: "C.S. Mott Children's Hospital",
    location: "Ann Arbor, MI",
    type: "hospital",
    beds: 348,
    referralsThisMonth: 18,
    referralsLastMonth: 15,
    acceptanceRate: 96,
    avgResponseTime: 1.1,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "phone"],
    contactPerson: "Dr. Michael Johnson, MD",
    phone: "(734) 936-4000",
    email: "peds.homecare@med.umich.edu",
    lastContact: "2024-01-15",
    priority: "high",
    estimatedMonthlyValue: 50000,
  },
  {
    id: "devos_childrens",
    name: "Helen DeVos Children's Hospital",
    location: "Grand Rapids, MI",
    type: "hospital",
    beds: 234,
    referralsThisMonth: 14,
    referralsLastMonth: 11,
    acceptanceRate: 93,
    avgResponseTime: 1.3,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "phone"],
    contactPerson: "Dr. Jennifer Davis, MD",
    phone: "(616) 267-0000",
    email: "peds.discharge@helendevoschildrens.org",
    lastContact: "2024-01-13",
    priority: "high",
    estimatedMonthlyValue: 39000,
  },
  {
    id: "karmanos_cancer",
    name: "Karmanos Cancer Institute",
    location: "Detroit, MI",
    type: "hospital",
    beds: 100,
    referralsThisMonth: 23,
    referralsLastMonth: 19,
    acceptanceRate: 88,
    avgResponseTime: 1.8,
    integrationStatus: "active",
    channels: ["epic_integration", "email", "phone"],
    contactPerson: "Dr. Lisa Martinez, MD",
    phone: "(313) 576-8000",
    email: "oncology.referrals@karmanos.org",
    lastContact: "2024-01-14",
    priority: "high",
    estimatedMonthlyValue: 64000,
  },

  // CRITICAL ACCESS HOSPITALS
  {
    id: "war_memorial",
    name: "War Memorial Hospital",
    location: "Sault Ste. Marie, MI",
    type: "hospital",
    beds: 49,
    referralsThisMonth: 8,
    referralsLastMonth: 7,
    acceptanceRate: 97,
    avgResponseTime: 1.0,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Jane Smith, RN",
    phone: "(906) 635-4400",
    email: "discharge.planning@warmemorialhospital.org",
    lastContact: "2024-01-15",
    priority: "medium",
    estimatedMonthlyValue: 22000,
  },
  {
    id: "mackinac_straits",
    name: "Mackinac Straits Health System",
    location: "St. Ignace, MI",
    type: "hospital",
    beds: 25,
    referralsThisMonth: 5,
    referralsLastMonth: 4,
    acceptanceRate: 95,
    avgResponseTime: 1.2,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Carol White, MSW",
    phone: "(906) 328-1400",
    email: "social.services@mshc.org",
    lastContact: "2024-01-14",
    priority: "medium",
    estimatedMonthlyValue: 14000,
  },
  {
    id: "munising_memorial",
    name: "Munising Memorial Hospital",
    location: "Munising, MI",
    type: "hospital",
    beds: 15,
    referralsThisMonth: 3,
    referralsLastMonth: 2,
    acceptanceRate: 98,
    avgResponseTime: 0.9,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Alice Green, RN",
    phone: "(906) 387-4100",
    email: "care.coordination@munisingmemorial.com",
    lastContact: "2024-01-13",
    priority: "medium",
    estimatedMonthlyValue: 8000,
  },
  {
    id: "baraga_county",
    name: "Baraga County Memorial Hospital",
    location: "L'Anse, MI",
    type: "hospital",
    beds: 20,
    referralsThisMonth: 4,
    referralsLastMonth: 3,
    acceptanceRate: 96,
    avgResponseTime: 1.1,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Betty Blue, MSW",
    phone: "(906) 524-3300",
    email: "patient.services@bcmh.org",
    lastContact: "2024-01-12",
    priority: "medium",
    estimatedMonthlyValue: 11000,
  },
  {
    id: "iron_river",
    name: "Aspirus Iron River Hospital",
    location: "Iron River, MI",
    type: "hospital",
    beds: 25,
    referralsThisMonth: 5,
    referralsLastMonth: 4,
    acceptanceRate: 94,
    avgResponseTime: 1.3,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Debra Black, RN",
    phone: "(906) 265-6121",
    email: "discharge.planning@aspirus.org",
    lastContact: "2024-01-14",
    priority: "medium",
    estimatedMonthlyValue: 14000,
  },
  {
    id: "iron_mountain",
    name: "Marshfield Medical Center- Dickinson",
    location: "Iron Mountain, MI",
    type: "hospital",
    beds: 49,
    referralsThisMonth: 8,
    referralsLastMonth: 7,
    acceptanceRate: 97,
    avgResponseTime: 1.0,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Cathy Grey, MSW",
    phone: "(906) 774-1313",
    email: "social.services@mmcl.org",
    lastContact: "2024-01-11",
    priority: "medium",
    estimatedMonthlyValue: 22000,
  },
  {
    id: "osceola_memorial",
    name: "Osceola Memorial Hospital",
    location: "Reed City, MI",
    type: "hospital",
    beds: 25,
    referralsThisMonth: 5,
    referralsLastMonth: 4,
    acceptanceRate: 95,
    avgResponseTime: 1.2,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Ethel Violet, RN",
    phone: "(231) 832-2244",
    email: "care.coordination@osceolamemorial.org",
    lastContact: "2024-01-13",
    priority: "medium",
    estimatedMonthlyValue: 14000,
  },
  {
    id: "paul_oliver",
    name: "Paul Oliver Memorial Hospital",
    location: "Frankfort, MI",
    type: "hospital",
    beds: 25,
    referralsThisMonth: 5,
    referralsLastMonth: 4,
    acceptanceRate: 96,
    avgResponseTime: 1.1,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Ingrid Indigo, MSW",
    phone: "(231) 352-2200",
    email: "patient.services@pomh.org",
    lastContact: "2024-01-12",
    priority: "medium",
    estimatedMonthlyValue: 14000,
  },
  {
    id: "bronner_clinic",
    name: "Bronner Clinic",
    location: "Frankenmuth, MI",
    type: "clinic",
    beds: 0,
    referralsThisMonth: 10,
    referralsLastMonth: 8,
    acceptanceRate: 90,
    avgResponseTime: 1.5,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Dr. Harvey Bronner",
    phone: "(989) 652-9900",
    email: "info@bronnerclinic.com",
    lastContact: "2024-01-15",
    priority: "low",
    estimatedMonthlyValue: 27000,
  },
  {
    id: "mid_michigan_ent",
    name: "Mid Michigan ENT & Allergy",
    location: "Midland, MI",
    type: "clinic",
    beds: 0,
    referralsThisMonth: 7,
    referralsLastMonth: 6,
    acceptanceRate: 85,
    avgResponseTime: 1.8,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Dr. James Martin",
    phone: "(989) 631-5900",
    email: "info@midmichiganent.com",
    lastContact: "2024-01-14",
    priority: "low",
    estimatedMonthlyValue: 19000,
  },
  {
    id: "allergy_and_asthma",
    name: "Allergy & Asthma Center of Michigan",
    location: "Ann Arbor, MI",
    type: "clinic",
    beds: 0,
    referralsThisMonth: 5,
    referralsLastMonth: 4,
    acceptanceRate: 80,
    avgResponseTime: 2.0,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Dr. Sarah Green",
    phone: "(734) 971-0800",
    email: "info@allergyasthmacenter.com",
    lastContact: "2024-01-13",
    priority: "low",
    estimatedMonthlyValue: 14000,
  },
  {
    id: "advanced_cardiology",
    name: "Advanced Cardiology Consultants",
    location: "Grand Rapids, MI",
    type: "clinic",
    beds: 0,
    referralsThisMonth: 8,
    referralsLastMonth: 7,
    acceptanceRate: 88,
    avgResponseTime: 1.7,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Dr. David Black",
    phone: "(616) 532-8800",
    email: "info@advancedcardiology.com",
    lastContact: "2024-01-12",
    priority: "low",
    estimatedMonthlyValue: 22000,
  },
  {
    id: "michigan_orthopedic",
    name: "Michigan Orthopedic Surgeons",
    location: "Kalamazoo, MI",
    type: "clinic",
    beds: 0,
    referralsThisMonth: 6,
    referralsLastMonth: 5,
    acceptanceRate: 82,
    avgResponseTime: 1.9,
    integrationStatus: "active",
    channels: ["email", "phone"],
    contactPerson: "Dr. Laura White",
    phone: "(269) 345-0600",
    email: "info@michiganorthopedic.com",
    lastContact: "2024-01-11",
    priority: "low",
    estimatedMonthlyValue: 16000,
  },
]

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const type = searchParams.get("type")
    const status = searchParams.get("status")
    const search = searchParams.get("search")

    let filteredSystems = [...healthSystems]

    // Filter by type
    if (type && type !== "all") {
      filteredSystems = filteredSystems.filter((system) => system.type === type)
    }

    // Filter by status
    if (status && status !== "all") {
      filteredSystems = filteredSystems.filter((system) => system.integrationStatus === status)
    }

    // Filter by search term
    if (search) {
      const searchLower = search.toLowerCase()
      filteredSystems = filteredSystems.filter(
        (system) =>
          system.name.toLowerCase().includes(searchLower) ||
          system.location.toLowerCase().includes(searchLower) ||
          system.contactPerson.toLowerCase().includes(searchLower),
      )
    }

    return NextResponse.json({
      success: true,
      data: filteredSystems,
      total: filteredSystems.length,
    })
  } catch (error) {
    console.error("Error fetching health systems:", error)
    return NextResponse.json({ success: false, error: "Failed to fetch health systems" }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { id, ...updates } = body

    // Find and update the health system
    const systemIndex = healthSystems.findIndex((system) => system.id === id)
    if (systemIndex === -1) {
      return NextResponse.json({ success: false, error: "Health system not found" }, { status: 404 })
    }

    healthSystems[systemIndex] = { ...healthSystems[systemIndex], ...updates }

    return NextResponse.json({
      success: true,
      data: healthSystems[systemIndex],
    })
  } catch (error) {
    console.error("Error updating health system:", error)
    return NextResponse.json({ success: false, error: "Failed to update health system" }, { status: 500 })
  }
}

export async function PUT(request: NextRequest) {
  try {
    const body = await request.json()
    const { id, integrationStatus, channels, contactPerson, phone, email } = body

    const systemIndex = healthSystems.findIndex((system) => system.id === id)
    if (systemIndex === -1) {
      return NextResponse.json({ success: false, error: "Health system not found" }, { status: 404 })
    }

    // Update integration settings
    healthSystems[systemIndex] = {
      ...healthSystems[systemIndex],
      integrationStatus,
      channels,
      contactPerson,
      phone,
      email,
      lastContact: new Date().toISOString().split("T")[0],
    }

    return NextResponse.json({
      success: true,
      data: healthSystems[systemIndex],
      message: "Integration settings updated successfully",
    })
  } catch (error) {
    console.error("Error updating integration settings:", error)
    return NextResponse.json({ success: false, error: "Failed to update integration settings" }, { status: 500 })
  }
}
