import { NextRequest, NextResponse } from "next/server"
import { createAdminClient } from "@/lib/supabase/server"

// GET /api/authorizations - Fetch all authorizations
export async function GET(request: NextRequest) {
  try {
    console.log("=== Fetching authorizations ===")
    
    const supabase = createAdminClient()
    const { searchParams } = new URL(request.url)
    
    // Get filter parameters
    const status = searchParams.get("status")
    const priority = searchParams.get("priority")
    const patientId = searchParams.get("patientId")
    const assignedStaffId = searchParams.get("assignedStaffId")
    const search = searchParams.get("search")

    // Build query
    let query = supabase
      .from("authorizations")
      .select("*")
      .order("submitted_date", { ascending: false })

    // Apply filters
    if (status && status !== "all") {
      query = query.eq("status", status)
    }

    if (priority && priority !== "all") {
      query = query.eq("priority", priority)
    }

    if (patientId) {
      query = query.eq("patient_id", patientId)
    }

    if (assignedStaffId) {
      query = query.eq("assigned_staff_id", assignedStaffId)
    }

    if (search) {
      query = query.ilike("patient_name", `%${search}%`)
    }

    console.log("Query filters:", { status, priority, patientId, assignedStaffId, search })

    const { data, error } = await query

    if (error) {
      console.error("❌ Supabase error:", error)
      return NextResponse.json({
        error: `Database error: ${error.message}`,
        details: error.details,
        hint: error.hint
      }, { status: 500 })
    }

    console.log(`✅ Fetched ${data?.length || 0} authorizations`)
    return NextResponse.json({ authorizations: data || [] })
  } catch (error) {
    console.error("❌ Error fetching authorizations:", error)
    const errorMessage = error instanceof Error ? error.message : "Unknown error"
    return NextResponse.json({
      error: `Internal server error: ${errorMessage}`
    }, { status: 500 })
  }
}

// POST /api/authorizations - Create a new authorization
export async function POST(request: NextRequest) {
  try {
    console.log("=== Creating authorization ===")
    
    const supabase = createAdminClient()
    const body = await request.json()
    
    console.log("Authorization data:", body)

    const {
      patientName,
      patientId,
      insuranceProvider,
      insuranceId,
      authorizationType,
      requestedServices,
      diagnosisCode,
      diagnosis,
      priority,
      estimatedReimbursement,
      assignedTo,
      assignedStaffId,
      referralId,
      reviewerNotes
    } = body

    // Validate required fields
    const requiredFields = {
      patientName,
      insuranceProvider,
      insuranceId,
      diagnosis
    }

    for (const [field, value] of Object.entries(requiredFields)) {
      if (!value) {
        console.error(`❌ Missing required field: ${field}`)
        return NextResponse.json({
          error: `Missing required field: ${field}`
        }, { status: 400 })
      }
    }

    // Create initial timeline entry
    const initialTimeline = [
      {
        date: new Date().toISOString(),
        action: "Authorization request submitted",
        user: "System",
        notes: reviewerNotes || undefined
      }
    ]

    // Prepare insert data
    const insertData = {
      patient_name: patientName,
      patient_id: patientId || null,
      insurance_provider: insuranceProvider,
      insurance_id: insuranceId,
      authorization_type: authorizationType || "initial",
      requested_services: requestedServices || [],
      diagnosis_code: diagnosisCode || null,
      diagnosis: diagnosis,
      status: "pending",
      priority: priority || "medium",
      estimated_reimbursement: estimatedReimbursement || 0,
      assigned_to: assignedTo || null,
      assigned_staff_id: assignedStaffId || null,
      referral_id: referralId || null,
      reviewer_notes: reviewerNotes || null,
      timeline: initialTimeline,
      submitted_date: new Date().toISOString().split('T')[0]
      // Note: created_at and updated_at are auto-generated by database
    }

    console.log("Inserting authorization:", insertData)

    const { data, error } = await supabase
      .from("authorizations")
      .insert(insertData)
      .select()
      .single()

    if (error) {
      console.error("❌ Supabase error:", error)
      return NextResponse.json({
        error: `Database error: ${error.message}`,
        details: error.details,
        hint: error.hint
      }, { status: 500 })
    }

    console.log("✅ Authorization created successfully:", data)
    return NextResponse.json({ authorization: data, success: true }, { status: 201 })
  } catch (error) {
    console.error("❌ Error creating authorization:", error)
    const errorMessage = error instanceof Error ? error.message : "Unknown error"
    return NextResponse.json({
      error: `Internal server error: ${errorMessage}`
    }, { status: 500 })
  }
}

