-- Add test employer for testing employer dashboard
INSERT INTO employers (
  id,
  first_name,
  last_name,
  email,
  phone,
  company_name,
  company_type,
  facility_size,
  city,
  state,
  zip_code,
  address,
  created_at,
  updated_at
) VALUES (
  '550e8400-e29b-41d4-a716-446655440001',
  'John',
  'Smith',
  'john.smith@serenityrehab.com',
  '(248) 555-0100',
  'Serenity Rehabilitation Center',
  'Healthcare',
  '50-200',
  'Detroit',
  'MI',
  '48201',
  '123 Healthcare Drive',
  NOW(),
  NOW()
);

-- Add a test job posting for this employer
INSERT INTO job_postings (
  id,
  employer_id,
  title,
  description,
  department,
  job_type,
  position_type,
  experience_required,
  education_required,
  requirements,
  benefits,
  salary_min,
  salary_max,
  salary_type,
  city,
  state,
  zip_code,
  created_at,
  updated_at
) VALUES (
  '550e8400-e29b-41d4-a716-446655440002',
  '550e8400-e29b-41d4-a716-446655440001',
  'Physical Therapist',
  'We are seeking a skilled Physical Therapist to join our team. The ideal candidate will have experience in outpatient rehabilitation and be passionate about helping patients recover and improve their quality of life.',
  'Physical Therapy',
  'Full-time',
  'Permanent',
  '2-5 years',
  'Doctorate in Physical Therapy',
  '• Valid PT license in Michigan\n• CPR certification\n• Experience with outpatient rehabilitation\n• Strong communication skills\n• Ability to work independently and as part of a team',
  '• Competitive salary\n• Health insurance\n• Dental insurance\n• Vision insurance\n• 401(k) matching\n• Paid time off\n• Continuing education allowance',
  75000,
  95000,
  'yearly',
  'Detroit',
  'MI',
  '48201',
  NOW(),
  NOW()
);

-- Add another job posting
INSERT INTO job_postings (
  id,
  employer_id,
  title,
  description,
  department,
  job_type,
  position_type,
  experience_required,
  education_required,
  requirements,
  benefits,
  salary_min,
  salary_max,
  salary_type,
  city,
  state,
  zip_code,
  created_at,
  updated_at
) VALUES (
  '550e8400-e29b-41d4-a716-446655440003',
  '550e8400-e29b-41d4-a716-446655440001',
  'Occupational Therapist',
  'Join our team as an Occupational Therapist and help patients regain independence in their daily activities. We offer a supportive environment with opportunities for professional growth.',
  'Occupational Therapy',
  'Full-time',
  'Permanent',
  '1-3 years',
  'Master''s in Occupational Therapy',
  '• Valid OT license in Michigan\n• CPR certification\n• Experience with adult rehabilitation\n• Knowledge of adaptive equipment\n• Strong assessment skills',
  '• Competitive salary\n• Health insurance\n• Dental insurance\n• Vision insurance\n• 401(k) matching\n• Paid time off\n• Professional development opportunities',
  70000,
  90000,
  'yearly',
  'Detroit',
  'MI',
  '48201',
  NOW(),
  NOW()
);
